### ISSUE TITLE
Actual analog axis support instead of mapping to digital keys?

### ISSUE THREAD

**Issue by rsn8887** [SonryP/VitaMote#1]
Android supports real analog controller inputs, as specified in the compatibility document here
https://static.googleusercontent.com/media/source.android.com/en//compatibility/android-cdd.pdf
on page 51:

Left analog stick: AXIS_X and AXIS_Y
Right analog stick: AXIS_Z and AXIS_Rz

It would be nice to support those, too. This would allow real analog control in games that support controllers.

**Comment by SonryP** [comment]
The problem now is that the MotionEvent is read only (from a real joystick), it is not used to simulate or send data as in the case of KeyEvent...
I have seen a couple of solutions that can help in something, but in that case it would only be for Root users...
