### ISSUE TITLE
Network error, please try again

### ISSUE THREAD

**Issue by four-hundred-and-twenty** [SonryP/VitaMote#3]
I always go through this when I try to connect after I get back to my phone. It's takes a long time to get it to finally connect. What's going on?

**Comment by ifohancroft** [comment]
@four-hundred-and-twenty I see you closed the issue. Did you end up solving the problem? How?

**Comment by SonryP** [comment]
I'm gonna work on this again, i think the major problem comes with newer android versions and apis.
